services:
  web:
    build: ./backend       # Путь к папке с Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend     # Монтирование кода (если нужно)
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/travel_db  # Исправлено localhost → db
      - PYTHONPATH=/
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: travel_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"  # Для доступа извне (опционально)
  pg_admin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
volumes:
  postgres_data: